import axios from 'axios';
import { ExchangeRateData, Currency } from '../types';

const API_KEY = '43fa388d3632a0e29f51b3d2';
const BASE_URL = 'https://v6.exchangerate-api.com/v6';

const exchangeRateApi = axios.create({
  baseURL: BASE_URL,
  timeout: 10000,
});

export const getExchangeRates = async (baseCurrency: string = 'USD'): Promise<ExchangeRateData> => {
  try {
    const response = await exchangeRateApi.get(`/${API_KEY}/latest/${baseCurrency}`);
    return response.data;
  } catch (error) {
    console.error('Error fetching exchange rates:', error);
    throw error;
  }
};

export const getSupportedCurrencies = async (): Promise<Currency[]> => {
  try {
    const response = await exchangeRateApi.get(`/${API_KEY}/codes`);
    
    if (response.data && response.data.supported_codes) {
      return response.data.supported_codes.map((code: string[]) => ({
        code: code[0],
        name: code[1],
      }));
    }
    
    throw new Error('Invalid response format');
  } catch (error) {
    console.error('Error fetching supported currencies:', error);
    throw error;
  }
};

export const getMockExchangeRates = (baseCurrency: string = 'USD'): ExchangeRateData => {
  const commonCurrencies: Record<string, number> = {
    USD: 1.0,
    AED: 3.6725,
    AFN: 70.9027,
    ALL: 86.8678,
    AMD: 389.4909,
    ANG: 1.79,
    AOA: 919.5038,
    ARS: 1178.5,
    AUD: 1.5453,
    AWG: 1.79,
    AZN: 1.6999,
    BAM: 1.7276,
    BBD: 2,
    BDT: 121.509,
    BGN: 1.7272,
    BHD: 0.376,
    BIF: 2955.587,
    BMD: 1,
    BND: 1.2901,
    BOB: 6.923,
    BRL: 5.6559,
    BSD: 1,
    BTN: 84.3505,
    BWP: 13.6143,
    BYN: 3.0413,
    BZD: 2,
    CAD: 1.381,
    CDF: 2886.1483,
    CHF: 0.8227,
    CLP: 946.7574,
    CNY: 7.2431,
    COP: 4254.9542,
    CRC: 505.9271,
    CUP: 24,
    CVE: 97.3966,
    CZK: 22.0005,
    DJF: 177.721,
    DKK: 6.5812,
    DOP: 58.8522,
    DZD: 132.6883,
    EGP: 50.6824,
    ERN: 15,
    ETB: 132.8428,
    EUR: 0.8833,
    FJD: 2.2468,
    FKP: 0.7521,
    FOK: 6.5813,
    GBP: 0.7521,
    GEL: 2.745,
    GGP: 0.7521,
    GHS: 13.7906,
    GIP: 0.7521,
    GMD: 72.7028,
    GNF: 8703.7978,
    GTQ: 7.7024,
    GYD: 209.2679,
    HKD: 7.7508,
    HNL: 25.9614,
    HRK: 6.6552,
    HTG: 130.6301,
    HUF: 356.3312,
    IDR: 16443.6105,
    ILS: 3.6151,
    IMP: 0.7521,
    INR: 84.3508,
    IQD: 1309.9884,
    IRR: 41995.6325,
    ISK: 129.111,
    JEP: 0.7521,
    JMD: 158.6626,
    JOD: 0.709,
    JPY: 143.7847,
    KES: 129.2058,
    KGS: 87.3506,
    KHR: 4032.03,
    KID: 1.5452,
    KMF: 434.5531,
    KRW: 1375.6102,
    KWD: 0.3066,
    KYD: 0.8333,
    KZT: 517.192,
    LAK: 21785.4162,
    LBP: 89500,
    LKR: 299.3162,
    LRD: 200.0157,
    LSL: 18.2768,
    LYD: 5.4595,
    MAD: 9.2385,
    MDL: 17.1997,
    MGA: 4446.0043,
    MKD: 54.2855,
    MMK: 2099.3614,
    MNT: 3543.6361,
    MOP: 7.9833,
    MRU: 39.8248,
    MUR: 45.3047,
    MVR: 15.451,
    MWK: 1742.5357,
    MXN: 19.6455,
    MYR: 4.2259,
    MZN: 63.9101,
    NAD: 18.2768,
    NGN: 1600.0604,
    NIO: 36.8143,
    NOK: 10.3932,
    NPR: 134.9609,
    NZD: 1.6757,
    OMR: 0.3845,
    PAB: 1,
    PEN: 3.6588,
    PGK: 4.0862,
    PHP: 55.6576,
    PKR: 281.164,
    PLN: 3.7678,
    PYG: 8046.4945,
    QAR: 3.64,
    RON: 4.389,
    RSD: 103.5255,
    RUB: 81.534,
    RWF: 1433.9697,
    SAR: 3.75,
    SBD: 8.5115,
    SCR: 14.6471,
    SDG: 453.9063,
    SEK: 9.6581,
    SGD: 1.2901,
    SHP: 0.7521,
    SLE: 22.7249,
    SLL: 22724.9437,
    SOS: 571.878,
    SRD: 36.6987,
    SSP: 4598.3522,
    STN: 21.6407,
    SYP: 12883.9004,
    SZL: 18.2768,
    THB: 32.92,
    TJS: 10.6067,
    TMT: 3.5,
    TND: 2.9927,
    TOP: 2.3547,
    TRY: 38.5967,
    TTD: 6.7909,
    TVD: 1.5452,
    TWD: 29.2122,
    TZS: 2677.519,
    UAH: 41.6165,
    UGX: 3655.2702,
    UYU: 41.9818,
    UZS: 12913.3931,
    VES: 88.7224,
    VND: 25982.324,
    VUV: 120.6716,
    WST: 2.7713,
    XAF: 579.4041,
    XCD: 2.7,
    XCG: 1.79,
    XDR: 0.7392,
    XOF: 579.4041,
    XPF: 105.4055,
    YER: 244.7999,
    ZAR: 18.2775,
    ZMW: 27.7202,
    ZWL: 6.8208
  };

  return {
    base_code: baseCurrency,
    conversion_rates: commonCurrencies,
    time_last_update_unix: Math.floor(Date.now() / 1000),
  };
};

export const getMockCurrencies = (): Currency[] => {
  return [
    { code: 'USD', name: 'United States Dollar' },
    { code: 'AED', name: 'United Arab Emirates Dirham' },
    { code: 'AFN', name: 'Afghan Afghani' },
    { code: 'ALL', name: 'Albanian Lek' },
    { code: 'AMD', name: 'Armenian Dram' },
    { code: 'ANG', name: 'Netherlands Antillean Guilder' },
    { code: 'AOA', name: 'Angolan Kwanza' },
    { code: 'ARS', name: 'Argentine Peso' },
    { code: 'AUD', name: 'Australian Dollar' },
    { code: 'AWG', name: 'Aruban Florin' },
    { code: 'AZN', name: 'Azerbaijani Manat' },
    { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark' },
    { code: 'BBD', name: 'Barbadian Dollar' },
    { code: 'BDT', name: 'Bangladeshi Taka' },
    { code: 'BGN', name: 'Bulgarian Lev' },
    { code: 'BHD', name: 'Bahraini Dinar' },
    { code: 'BIF', name: 'Burundian Franc' },
    { code: 'BMD', name: 'Bermudan Dollar' },
    { code: 'BND', name: 'Brunei Dollar' },
    { code: 'BOB', name: 'Bolivian Boliviano' },
    { code: 'BRL', name: 'Brazilian Real' },
    { code: 'BSD', name: 'Bahamian Dollar' },
    { code: 'BTN', name: 'Bhutanese Ngultrum' },
    { code: 'BWP', name: 'Botswanan Pula' },
    { code: 'BYN', name: 'Belarusian Ruble' },
    { code: 'BZD', name: 'Belize Dollar' },
    { code: 'CAD', name: 'Canadian Dollar' },
    { code: 'CDF', name: 'Congolese Franc' },
    { code: 'CHF', name: 'Swiss Franc' },
    { code: 'CLP', name: 'Chilean Peso' },
    { code: 'CNY', name: 'Chinese Yuan' },
    { code: 'COP', name: 'Colombian Peso' },
    { code: 'CRC', name: 'Costa Rican Colón' },
    { code: 'CUP', name: 'Cuban Peso' },
    { code: 'CVE', name: 'Cape Verdean Escudo' },
    { code: 'CZK', name: 'Czech Republic Koruna' },
    { code: 'DJF', name: 'Djiboutian Franc' },
    { code: 'DKK', name: 'Danish Krone' },
    { code: 'DOP', name: 'Dominican Peso' },
    { code: 'DZD', name: 'Algerian Dinar' },
    { code: 'EGP', name: 'Egyptian Pound' },
    { code: 'ERN', name: 'Eritrean Nakfa' },
    { code: 'ETB', name: 'Ethiopian Birr' },
    { code: 'EUR', name: 'Euro' },
    { code: 'FJD', name: 'Fijian Dollar' },
    { code: 'FKP', name: 'Falkland Islands Pound' },
    { code: 'FOK', name: 'Faroese Króna' },
    { code: 'GBP', name: 'British Pound Sterling' },
    { code: 'GEL', name: 'Georgian Lari' },
    { code: 'GGP', name: 'Guernsey Pound' },
    { code: 'GHS', name: 'Ghanaian Cedi' },
    { code: 'GIP', name: 'Gibraltar Pound' },
    { code: 'GMD', name: 'Gambian Dalasi' },
    { code: 'GNF', name: 'Guinean Franc' },
    { code: 'GTQ', name: 'Guatemalan Quetzal' },
    { code: 'GYD', name: 'Guyanaese Dollar' },
    { code: 'HKD', name: 'Hong Kong Dollar' },
    { code: 'HNL', name: 'Honduran Lempira' },
    { code: 'HRK', name: 'Croatian Kuna' },
    { code: 'HTG', name: 'Haitian Gourde' },
    { code: 'HUF', name: 'Hungarian Forint' },
    { code: 'IDR', name: 'Indonesian Rupiah' },
    { code: 'ILS', name: 'Israeli New Shekel' },
    { code: 'IMP', name: 'Manx pound' },
    { code: 'INR', name: 'Indian Rupee' },
    { code: 'IQD', name: 'Iraqi Dinar' },
    { code: 'IRR', name: 'Iranian Rial' },
    { code: 'ISK', name: 'Icelandic Króna' },
    { code: 'JEP', name: 'Jersey Pound' },
    { code: 'JMD', name: 'Jamaican Dollar' },
    { code: 'JOD', name: 'Jordanian Dinar' },
    { code: 'JPY', name: 'Japanese Yen' },
    { code: 'KES', name: 'Kenyan Shilling' },
    { code: 'KGS', name: 'Kyrgystani Som' },
    { code: 'KHR', name: 'Cambodian Riel' },
    { code: 'KID', name: 'Kiribati Dollar' },
    { code: 'KMF', name: 'Comorian Franc' },
    { code: 'KRW', name: 'South Korean Won' },
    { code: 'KWD', name: 'Kuwaiti Dinar' },
    { code: 'KYD', name: 'Cayman Islands Dollar' },
    { code: 'KZT', name: 'Kazakhstani Tenge' },
    { code: 'LAK', name: 'Laotian Kip' },
    { code: 'LBP', name: 'Lebanese Pound' },
    { code: 'LKR', name: 'Sri Lankan Rupee' },
    { code: 'LRD', name: 'Liberian Dollar' },
    { code: 'LSL', name: 'Lesotho Loti' },
    { code: 'LYD', name: 'Libyan Dinar' },
    { code: 'MAD', name: 'Moroccan Dirham' },
    { code: 'MDL', name: 'Moldovan Leu' },
    { code: 'MGA', name: 'Malagasy Ariary' },
    { code: 'MKD', name: 'Macedonian Denar' },
    { code: 'MMK', name: 'Myanma Kyat' },
    { code: 'MNT', name: 'Mongolian Tugrik' },
    { code: 'MOP', name: 'Macanese Pataca' },
    { code: 'MRU', name: 'Mauritanian Ouguiya' },
    { code: 'MUR', name: 'Mauritian Rupee' },
    { code: 'MVR', name: 'Maldivian Rufiyaa' },
    { code: 'MWK', name: 'Malawian Kwacha' },
    { code: 'MXN', name: 'Mexican Peso' },
    { code: 'MYR', name: 'Malaysian Ringgit' },
    { code: 'MZN', name: 'Mozambican Metical' },
    { code: 'NAD', name: 'Namibian Dollar' },
    { code: 'NGN', name: 'Nigerian Naira' },
    { code: 'NIO', name: 'Nicaraguan Córdoba' },
    { code: 'NOK', name: 'Norwegian Krone' },
    { code: 'NPR', name: 'Nepalese Rupee' },
    { code: 'NZD', name: 'New Zealand Dollar' },
    { code: 'OMR', name: 'Omani Rial' },
    { code: 'PAB', name: 'Panamanian Balboa' },
    { code: 'PEN', name: 'Peruvian Nuevo Sol' },
    { code: 'PGK', name: 'Papua New Guinean Kina' },
    { code: 'PHP', name: 'Philippine Peso' },
    { code: 'PKR', name: 'Pakistani Rupee' },
    { code: 'PLN', name: 'Polish Złoty' },
    { code: 'PYG', name: 'Paraguayan Guarani' },
    { code: 'QAR', name: 'Qatari Rial' },
    { code: 'RON', name: 'Romanian Leu' },
    { code: 'RSD', name: 'Serbian Dinar' },
    { code: 'RUB', name: 'Russian Ruble' },
    { code: 'RWF', name: 'Rwandan Franc' },
    { code: 'SAR', name: 'Saudi Riyal' },
    { code: 'SBD', name: 'Solomon Islands Dollar' },
    { code: 'SCR', name: 'Seychellois Rupee' },
    { code: 'SDG', name: 'Sudanese Pound' },
    { code: 'SEK', name: 'Swedish Krona' },
    { code: 'SGD', name: 'Singapore Dollar' },
    { code: 'SHP', name: 'Saint Helena Pound' },
    { code: 'SLE', name: 'Sierra Leonean Leone' },
    { code: 'SLL', name: 'Sierra Leonean Leone (Old)' },
    { code: 'SOS', name: 'Somali Shilling' },
    { code: 'SRD', name: 'Surinamese Dollar' },
    { code: 'SSP', name: 'South Sudanese Pound' },
    { code: 'STN', name: 'São Tomé and Príncipe Dobra' },
    { code: 'SYP', name: 'Syrian Pound' },
    { code: 'SZL', name: 'Swazi Lilangeni' },
    { code: 'THB', name: 'Thai Baht' },
    { code: 'TJS', name: 'Tajikistani Somoni' },
    { code: 'TMT', name: 'Turkmenistani Manat' },
    { code: 'TND', name: 'Tunisian Dinar' },
    { code: 'TOP', name: 'Tongan Paʻanga' },
    { code: 'TRY', name: 'Turkish Lira' },
    { code: 'TTD', name: 'Trinidad and Tobago Dollar' },
    { code: 'TVD', name: 'Tuvaluan Dollar' },
    { code: 'TWD', name: 'New Taiwan Dollar' },
    { code: 'TZS', name: 'Tanzanian Shilling' },
    { code: 'UAH', name: 'Ukrainian Hryvnia' },
    { code: 'UGX', name: 'Ugandan Shilling' },
    { code: 'UYU', name: 'Uruguayan Peso' },
    { code: 'UZS', name: 'Uzbekistan Som' },
    { code: 'VES', name: 'Venezuelan Bolívar Soberano' },
    { code: 'VND', name: 'Vietnamese Dong' },
    { code: 'VUV', name: 'Vanuatu Vatu' },
    { code: 'WST', name: 'Samoan Tala' },
    { code: 'XAF', name: 'CFA Franc BEAC' },
    { code: 'XCD', name: 'East Caribbean Dollar' },
    { code: 'XCG', name: 'CFA Franc BCEAO' },
    { code: 'XDR', name: 'Special Drawing Rights' },
    { code: 'XOF', name: 'CFA Franc BCEAO' },
    { code: 'XPF', name: 'CFP Franc' },
    { code: 'YER', name: 'Yemeni Rial' },
    { code: 'ZAR', name: 'South African Rand' },
    { code: 'ZMW', name: 'Zambian Kwacha' },
    { code: 'ZWL', name: 'Zimbabwean Dollar' }
  ];
};